Delete Config Files with `make uninstall`
ErikBoesen/psc pull request #17
Opened 2019-12-09 23:37 UTC by Matt-Gleich

Due to the fact that very important credentials are held in these config files, they should be deleted upon uninstall.

2019-12-09 23:46 UTC, ErikBoesen requested changes
Would prefer that this be done in a separate make task, called `purge` like in apt. Usually uninstallation programs on Unix-based systems don't remove config files by default, I think. Very good catch though.

2019-12-10 01:21 UTC, ErikBoesen requested changes
Can you make purge require uninstall as well? So replace the line `purge:` with `purge: uninstall`

2019-12-10 16:09 UTC, ErikBoesen requested changes

2019-12-10 16:09 UTC, ErikBoesen commented on README.md
> +To cleanup credentials located at root (you should run after uninstall):
Last nitpick: you don't need to run this after install as it does the uninstall automatically, so maybe say to run this instead if you want to purge config files as well.

2019-12-10 18:50 UTC, ErikBoesen approved these changes
Good work! Sorry for all the nitpicking haha

2019-12-10 18:51 UTC, merged

2019-12-10 19:30 UTC, Matt-Gleich commented
Nah your good lol. Thanks for accepting!